name: Dispatch Command

on:
  issue_comment:
    types: [created]

jobs:
  dispatch-command:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch /rebase Command
        uses: peter-evans/slash-command-dispatch@2afb49dbaafaba8005860648bf7fc178637aca0d
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          reaction-token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          commands: rebase
          permission: triage
          issue-type: pull-request
